openapi: 3.0.0

info:
  description: |-
    ## 使用注意

    这是 erda 的 openapi 服务接口，例如 openapi.erda.cloud，并且需要带上请求头 “Org”，值为组织名称，例如 “terminus”
  title: erda-trantor
  version: "1.0"

paths:
  /api/applications:
    post:
      operationId: 创建应用
      requestBody:
        content:
          application/json:
            schema:
              example:
                isExternalRepo: true
                mode: SERVICE
                name: trantor
                projectId: 1
                repoConfig:
                  desc: Example
                  password: xxxxx
                  type: general
                  url: https://erda.cloud/terminus/dop/xxx/ss-dice-test
                  username: git
              properties:
                isExternalRepo:
                  description: 是否使用外置仓库
                  example: true
                  type: boolean
                  x-dice-name: isExternalRepo
                  x-dice-required: true
                mode:
                  description: 应用类型，一般填 SERVICE，表示可部署的应用
                  enum:
                    - SERVICE
                  example: SERVICE
                  type: string
                  x-dice-name: mode
                  x-dice-required: true
                name:
                  description: 应用名称
                  example: trantor
                  type: string
                  x-dice-name: name
                  x-dice-required: true
                projectId:
                  description: 应用所属项目的 ID
                  example: 1
                  type: number
                  x-dice-name: projectId
                  x-dice-required: true
                repoConfig:
                  description: 外置仓库配置
                  example:
                    desc: Example
                    password: xxxxx
                    type: general
                    url: https://erda.cloud/terminus/dop/xxx/ss-dice-test
                    username: git
                  properties:
                    desc:
                      description: 外置仓库描述
                      example: Example
                      type: string
                      x-dice-name: desc
                      x-dice-required: false
                    password:
                      description: 外置仓库密码
                      example: xxxxx
                      type: string
                      x-dice-name: password
                      x-dice-required: true
                    type:
                      description: 外置仓库类型，一般填 general
                      enum:
                        - general
                      example: general
                      type: string
                      x-dice-name: type
                      x-dice-required: true
                    url:
                      description: 外置仓库地址
                      example: https://erda.cloud/terminus/dop/xxx/ss-dice-test
                      type: string
                      x-dice-name: url
                      x-dice-required: true
                    username:
                      description: 外置仓库用户名
                      example: git
                      type: string
                      x-dice-name: username
                      x-dice-required: true
                  required:
                    - type
                    - url
                    - username
                    - password
                  type: object
                  x-dice-name: repoConfig
                  x-dice-required: false
              required:
                - name
                - mode
                - projectId
                - isExternalRepo
              type: object
              x-dice-media: application/json
              x-dice-name: schema
      responses:
        "200":
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/StandardResult'
                example:
                  err:
                    msg: failed
                  success: true
                type: object
                x-dice-media: application/json
                x-dice-name: schema
          description: ""
      summary: 创建应用
      tags:
        - 应用管理
  /api/cicds:
    post:
      operationId: 创建流水线
      requestBody:
        content:
          application/json:
            schema:
              example:
                appID: "5880"
                branch: feature/auto-test1
                pipelineYmlName: pipeline.yml
                pipelineYmlSource: gittar
                source: dice
              properties:
                appID:
                  description: 应用ID
                  example: "5880"
                  type: string
                  x-dice-name: appID
                  x-dice-required: true
                branch:
                  description: 分支名称
                  example: feature/auto-test1
                  type: string
                  x-dice-name: branch
                  x-dice-required: true
                pipelineYmlName:
                  default: ""
                  description: 对应的流水线文件名称，默认流水线是 pipeline.yml
                  example: pipeline.yml
                  type: string
                  x-dice-name: pipelineYmlName
                  x-dice-required: true
                pipelineYmlSource:
                  enum:
                    - gittar
                  example: gittar
                  type: string
                  x-dice-name: pipelineYmlSource
                  x-dice-required: true
                source:
                  enum:
                    - dice
                  example: dice
                  type: string
                  x-dice-name: source
                  x-dice-required: true
              required:
                - appID
                - branch
                - pipelineYmlName
                - pipelineYmlSource
                - source
              type: object
              x-dice-media: application/json
              x-dice-name: schema
      responses:
        "200":
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/StandardResult'
                example:
                  err:
                    msg: failed
                  success: true
                type: object
                x-dice-media: application/json
                x-dice-name: schema
          description: ""
      summary: 创建流水线
      tags:
        - 流水线管理
  /api/configmanage/configs:
    get:
      operationId: 获取应用环境变量
      parameters:
        - in: query
          name: appID
          required: true
          schema:
            description: 应用ID
            example: "5880"
            type: string
            x-dice-name: appID
            x-dice-required: true
          x-dice-name: appID
        - in: query
          name: namespace_name
          required: true
          schema:
            description: |-
              环境空间，字段拼接规则为：app-应用ID-环境缩写，例如: app-5880-DEV、app-5880-TEST、app-5880-STAGING、app-5880-PROD
              还可以写 app-5880-DEFAULT，表示四个环境可共用的默认配置
            example: app-5880-DEV
            type: string
            x-dice-name: namespace_name
            x-dice-required: true
          x-dice-name: namespace_name
      responses:
        "200":
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/StandardResult'
                example:
                  data:
                    - key: Example
                      type: kv
                      value: Example
                  err:
                    msg: failed
                  success: true
                properties:
                  data:
                    description: 配置项列表
                    example:
                      - key: Example
                        type: kv
                        value: Example
                    items:
                      allOf:
                        - $ref: '#/components/schemas/ConfigItem'
                      example:
                        key: Example
                        type: kv
                        value: Example
                      type: object
                      x-dice-name: items
                    type: array
                    x-dice-name: data
                    x-dice-required: true
                required:
                  - data
                type: object
                x-dice-media: application/json
                x-dice-name: schema
          description: ""
      summary: 获取应用环境变量
      tags:
        - 应用管理
    post:
      description: 支持批量添加环境变量
      operationId: 新增应用配置项
      parameters:
        - in: query
          name: appID
          required: true
          schema:
            description: 应用ID
            example: "5880"
            type: string
            x-dice-name: appID
            x-dice-required: true
          x-dice-name: appID
        - in: query
          name: encrypt
          required: true
          schema:
            description: 是否需要加密，一般为 false
            example: false
            type: boolean
            x-dice-name: encrypt
            x-dice-required: true
          x-dice-name: encrypt
        - in: query
          name: namespace_name
          required: true
          schema:
            description: |-
              环境空间，字段拼接规则为：app-应用ID-环境缩写，例如: app-5880-DEV、app-5880-TEST、app-5880-STAGING、app-5880-PROD
              还可以写 app-5880-DEFAULT，表示四个环境可共用的默认配置
            example: app-5880-DEV
            type: string
            x-dice-name: namespace_name
            x-dice-required: true
          x-dice-name: namespace_name
      requestBody:
        content:
          application/json:
            schema:
              example:
                configs:
                  - key: Example
                    type: kv
                    value: Example
              properties:
                configs:
                  description: 要添加的配置项
                  example:
                    - key: Example
                      type: kv
                      value: Example
                  items:
                    allOf:
                      - $ref: '#/components/schemas/ConfigItem'
                    example:
                      key: Example
                      type: kv
                      value: Example
                    type: object
                    x-dice-name: items
                  type: array
                  x-dice-name: configs
                  x-dice-required: true
              required:
                - configs
              type: object
              x-dice-media: application/json
              x-dice-name: schema
      responses:
        "200":
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/StandardResult'
                example:
                  err:
                    msg: failed
                  success: true
                type: object
                x-dice-media: application/json
                x-dice-name: schema
          description: ""
      summary: 新增应用配置项
      tags:
        - 应用管理
  /api/gateway/openapi/packages:
    get:
      description: 获取流量入口列表中，scene 为 unity 的流量入口的 bindDomain 中的第一个，即为 trantor 使用的网关域名
      operationId: API网关流量入口列表
      parameters:
        - in: query
          name: projectId
          required: true
          schema:
            description: 项目 ID
            example: 1
            type: number
            x-dice-name: projectId
            x-dice-required: true
          x-dice-name: projectId
        - in: query
          name: env
          required: true
          schema:
            description: 环境
            enum:
              - DEV
              - TEST
              - STAGING
              - PROD
            example: DEV
            type: string
            x-dice-name: env
            x-dice-required: true
          x-dice-name: env
      responses:
        "200":
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/StandardResult'
                example:
                  data:
                    list:
                      - bindDomain:
                          - test-gateway.hkci.terminus.io
                        id: Example
                        scene: unity
                  err:
                    msg: failed
                  success: true
                properties:
                  data:
                    example:
                      list:
                        - bindDomain:
                            - test-gateway.hkci.terminus.io
                          id: Example
                          scene: unity
                    properties:
                      list:
                        example:
                          - bindDomain:
                              - test-gateway.hkci.terminus.io
                            id: Example
                            scene: unity
                        items:
                          allOf:
                            - $ref: '#/components/schemas/GatewayEndpoint'
                          example:
                            bindDomain:
                              - test-gateway.hkci.terminus.io
                            id: Example
                            scene: unity
                          type: object
                          x-dice-name: items
                        type: array
                        x-dice-name: list
                        x-dice-required: true
                    required:
                      - list
                    type: object
                    x-dice-name: data
                    x-dice-required: true
                required:
                  - data
                type: object
                x-dice-media: application/json
                x-dice-name: schema
          description: ""
      summary: API网关流量入口列表
      tags:
        - API网关
  /api/projects:
    get:
      description: 分页查询项目
      operationId: 项目列出
      parameters:
        - in: query
          name: orgId
          required: true
          schema:
            example: 1
            type: integer
            x-dice-name: orgId
            x-dice-required: true
          x-dice-name: orgId
        - in: query
          name: q
          schema:
            description: 按项目名称搜索
            example: dop
            type: string
            x-dice-name: q
            x-dice-required: false
          x-dice-name: q
        - in: query
          name: pageSize
          schema:
            default: 20
            example: 20
            type: integer
            x-dice-name: pageSize
            x-dice-required: false
          x-dice-name: pageSize
        - in: query
          name: pageNo
          schema:
            default: 1
            example: 1
            type: integer
            x-dice-name: pageNo
            x-dice-required: false
          x-dice-name: pageNo
        - in: query
          name: is_public
          schema:
            default: false
            description: 是否为公开项目
            example: true
            type: boolean
            x-dice-name: is_public
            x-dice-required: false
          x-dice-name: is_public
        - in: query
          name: asc
          schema:
            description: 是否升序
            example: true
            type: boolean
            x-dice-name: asc
            x-dice-required: false
          x-dice-name: asc
        - in: query
          name: orderBy
          schema:
            example: activeTime
            type: string
            x-dice-name: orderBy
            x-dice-required: false
          x-dice-name: orderBy
      responses:
        "200":
          content:
            application/json:
              schema:
                example:
                  data:
                    list:
                      - CanManage: true
                        activeTime: "2021-09-24 15:07:14"
                        blockStatus: Example
                        canUnblock: Example
                        clusterConfig:
                          DEV: Example
                          PROD: Example
                          STAGING: Example
                          TEST: Example
                        cpuAddonUsed: 1
                        cpuQuota: 1
                        cpuServiceUsed: 1
                        createdAt: "2021-09-24T15:07:14+08:00"
                        creator: "2"
                        ddHook: Example
                        desc: Example
                        displayName: Example
                        id: 1
                        isPublic: true
                        joined: true
                        logo: Example
                        memAddonUsed: 1
                        memQuota: 1
                        memServiceUsed: 1
                        name: Example
                        orgId: 1
                        owners:
                          - Example
                        type: DevOps
                        updatedAt: "2021-09-24T15:07:14+08:00"
                    total: 11
                properties:
                  data:
                    example:
                      list:
                        - CanManage: true
                          activeTime: "2021-09-24 15:07:14"
                          blockStatus: Example
                          canUnblock: Example
                          clusterConfig:
                            DEV: Example
                            PROD: Example
                            STAGING: Example
                            TEST: Example
                          cpuAddonUsed: 1
                          cpuQuota: 1
                          cpuServiceUsed: 1
                          createdAt: "2021-09-24T15:07:14+08:00"
                          creator: "2"
                          ddHook: Example
                          desc: Example
                          displayName: Example
                          id: 1
                          isPublic: true
                          joined: true
                          logo: Example
                          memAddonUsed: 1
                          memQuota: 1
                          memServiceUsed: 1
                          name: Example
                          orgId: 1
                          owners:
                            - Example
                          type: DevOps
                          updatedAt: "2021-09-24T15:07:14+08:00"
                      total: 11
                    properties:
                      list:
                        description: 项目列表
                        example:
                          - CanManage: true
                            activeTime: "2021-09-24 15:07:14"
                            blockStatus: Example
                            canUnblock: Example
                            clusterConfig:
                              DEV: Example
                              PROD: Example
                              STAGING: Example
                              TEST: Example
                            cpuAddonUsed: 1
                            cpuQuota: 1
                            cpuServiceUsed: 1
                            createdAt: "2021-09-24T15:07:14+08:00"
                            creator: "2"
                            ddHook: Example
                            desc: Example
                            displayName: Example
                            id: 1
                            isPublic: true
                            joined: true
                            logo: Example
                            memAddonUsed: 1
                            memQuota: 1
                            memServiceUsed: 1
                            name: Example
                            orgId: 1
                            owners:
                              - Example
                            type: DevOps
                            updatedAt: "2021-09-24T15:07:14+08:00"
                        items:
                          example:
                            CanManage: true
                            activeTime: "2021-09-24 15:07:14"
                            blockStatus: Example
                            canUnblock: Example
                            clusterConfig:
                              DEV: Example
                              PROD: Example
                              STAGING: Example
                              TEST: Example
                            cpuAddonUsed: 1
                            cpuQuota: 1
                            cpuServiceUsed: 1
                            createdAt: "2021-09-24T15:07:14+08:00"
                            creator: "2"
                            ddHook: Example
                            desc: Example
                            displayName: Example
                            id: 1
                            isPublic: true
                            joined: true
                            logo: Example
                            memAddonUsed: 1
                            memQuota: 1
                            memServiceUsed: 1
                            name: Example
                            orgId: 1
                            owners:
                              - Example
                            type: DevOps
                            updatedAt: "2021-09-24T15:07:14+08:00"
                          properties:
                            CanManage:
                              example: true
                              type: boolean
                              x-dice-name: CanManage
                              x-dice-required: true
                            activeTime:
                              example: "2021-09-24 15:07:14"
                              type: string
                              x-dice-name: activeTime
                              x-dice-required: true
                            blockStatus:
                              example: Example
                              type: string
                              x-dice-name: blockStatus
                              x-dice-required: true
                            canUnblock:
                              example: Example
                              type: string
                              x-dice-name: canUnblock
                              x-dice-required: true
                            clusterConfig:
                              example:
                                DEV: Example
                                PROD: Example
                                STAGING: Example
                                TEST: Example
                              properties:
                                DEV:
                                  example: Example
                                  type: string
                                  x-dice-name: DEV
                                  x-dice-required: true
                                PROD:
                                  example: Example
                                  type: string
                                  x-dice-name: PROD
                                  x-dice-required: true
                                STAGING:
                                  example: Example
                                  type: string
                                  x-dice-name: STAGING
                                  x-dice-required: true
                                TEST:
                                  example: Example
                                  type: string
                                  x-dice-name: TEST
                                  x-dice-required: true
                              required:
                                - DEV
                                - PROD
                                - STAGING
                                - TEST
                              type: object
                              x-dice-name: clusterConfig
                              x-dice-required: true
                            cpuAddonUsed:
                              example: 1
                              type: integer
                              x-dice-name: cpuAddonUsed
                              x-dice-required: true
                            cpuQuota:
                              example: 1
                              type: integer
                              x-dice-name: cpuQuota
                              x-dice-required: true
                            cpuServiceUsed:
                              example: 1
                              type: integer
                              x-dice-name: cpuServiceUsed
                              x-dice-required: true
                            createdAt:
                              example: "2021-09-24T15:07:14+08:00"
                              type: string
                              x-dice-name: createdAt
                              x-dice-required: true
                            creator:
                              description: 创建者ID
                              example: "2"
                              type: string
                              x-dice-name: creator
                              x-dice-required: true
                            ddHook:
                              example: Example
                              type: string
                              x-dice-name: ddHook
                              x-dice-required: true
                            desc:
                              example: Example
                              type: string
                              x-dice-name: desc
                              x-dice-required: true
                            displayName:
                              example: Example
                              type: string
                              x-dice-name: displayName
                              x-dice-required: true
                            id:
                              description: 项目ID
                              example: 1
                              type: integer
                              x-dice-name: id
                              x-dice-required: true
                            isPublic:
                              example: true
                              type: boolean
                              x-dice-name: isPublic
                              x-dice-required: true
                            joined:
                              example: true
                              type: boolean
                              x-dice-name: joined
                              x-dice-required: true
                            logo:
                              example: Example
                              type: string
                              x-dice-name: logo
                              x-dice-required: true
                            memAddonUsed:
                              example: 1
                              type: integer
                              x-dice-name: memAddonUsed
                              x-dice-required: true
                            memQuota:
                              example: 1
                              type: integer
                              x-dice-name: memQuota
                              x-dice-required: true
                            memServiceUsed:
                              example: 1
                              type: integer
                              x-dice-name: memServiceUsed
                              x-dice-required: true
                            name:
                              description: 项目名称
                              example: Example
                              type: string
                              x-dice-name: name
                              x-dice-required: true
                            orgId:
                              example: 1
                              type: integer
                              x-dice-name: orgId
                              x-dice-required: true
                            owners:
                              description: 项目所有者ID列表
                              example:
                                - Example
                              items:
                                example: Example
                                type: string
                                x-dice-name: items
                              type: array
                              x-dice-name: owners
                              x-dice-required: true
                            type:
                              example: DevOps
                              type: string
                              x-dice-name: type
                              x-dice-required: true
                            updatedAt:
                              example: "2021-09-24T15:07:14+08:00"
                              type: string
                              x-dice-name: updatedAt
                              x-dice-required: true
                          required:
                            - CanManage
                            - activeTime
                            - blockStatus
                            - canUnblock
                            - clusterConfig
                            - cpuAddonUsed
                            - cpuQuota
                            - cpuServiceUsed
                            - createdAt
                            - creator
                            - ddHook
                            - desc
                            - displayName
                            - id
                            - isPublic
                            - joined
                            - logo
                            - memAddonUsed
                            - memQuota
                            - memServiceUsed
                            - name
                            - orgId
                            - owners
                            - type
                            - updatedAt
                          type: object
                          x-dice-name: items
                        type: array
                        x-dice-name: list
                        x-dice-required: true
                      total:
                        description: 总数
                        example: 11
                        type: integer
                        x-dice-name: total
                        x-dice-required: true
                    required:
                      - list
                      - total
                    type: object
                    x-dice-name: data
                    x-dice-required: true
                required:
                  - data
                type: object
                x-dice-media: application/json
          description: ""
      summary: 项目列出
      tags:
        - 项目管理
    post:
      operationId: 项目新建
      requestBody:
        content:
          application/json:
            schema:
              example:
                clusterConfig:
                  DEV: terminus-dev
                  PROD: terminus-dev
                  STAGING: terminus-dev
                  TEST: terminus-dev
                clusterId: 1
                clusterName: Example
                cpuQuota: 1
                creator: Example
                ddHook: Example
                desc: Example
                displayName: dop-apis
                memQuota: 1
                name: dop-apis
                orgId: 1
                rollbackConfig: {}
                template: DevOps
              properties:
                clusterConfig:
                  description: |-
                    项目各环境集群配置
                    map[string]string
                  example:
                    DEV: terminus-dev
                    PROD: terminus-dev
                    STAGING: terminus-dev
                    TEST: terminus-dev
                  properties:
                    DEV:
                      example: terminus-dev
                      type: string
                      x-dice-name: DEV
                      x-dice-required: true
                    PROD:
                      example: terminus-dev
                      type: string
                      x-dice-name: PROD
                      x-dice-required: true
                    STAGING:
                      example: terminus-dev
                      type: string
                      x-dice-name: STAGING
                      x-dice-required: true
                    TEST:
                      example: terminus-dev
                      type: string
                      x-dice-name: TEST
                      x-dice-required: true
                  required:
                    - DEV
                    - TEST
                    - STAGING
                    - PROD
                  type: object
                  x-dice-name: clusterConfig
                  x-dice-required: true
                clusterId:
                  description: 集群ID
                  example: 1
                  type: integer
                  x-dice-name: clusterId
                  x-dice-required: false
                clusterName:
                  description: 集群名称
                  example: Example
                  type: string
                  x-dice-name: clusterName
                  x-dice-required: false
                cpuQuota:
                  description: cpu配额
                  example: 1
                  type: integer
                  x-dice-name: cpuQuota
                  x-dice-required: true
                creator:
                  description: 创建者的用户id
                  example: Example
                  type: string
                  x-dice-name: creator
                  x-dice-required: true
                ddHook:
                  description: 项目级别的钉钉回调地址
                  example: Example
                  type: string
                  x-dice-name: ddHook
                  x-dice-required: false
                desc:
                  description: 描述
                  example: Example
                  type: string
                  x-dice-name: desc
                  x-dice-required: false
                displayName:
                  description: 项目别名
                  example: dop-apis
                  type: string
                  x-dice-name: displayName
                  x-dice-required: true
                memQuota:
                  description: 内存配额
                  example: 1
                  type: integer
                  x-dice-name: memQuota
                  x-dice-required: true
                name:
                  description: 项目名称
                  example: dop-apis
                  type: string
                  x-dice-name: name
                  x-dice-required: true
                orgId:
                  description: 组织ID
                  example: 1
                  type: integer
                  x-dice-name: orgId
                  x-dice-required: true
                rollbackConfig:
                  description: 项目回滚点配置 map[string]int
                  example: {}
                  type: object
                  x-dice-name: rollbackConfig
                  x-dice-required: false
                template:
                  example: DevOps
                  type: string
                  x-dice-name: template
                  x-dice-required: true
              required:
                - clusterConfig
                - cpuQuota
                - creator
                - displayName
                - memQuota
                - name
                - orgId
                - template
              type: object
              x-dice-media: application/json
              x-dice-name: schema
      responses:
        "200":
          content:
            application/json:
              schema:
                example:
                  data: 11
                  success: true
                properties:
                  data:
                    description: 项目ID
                    example: 11
                    type: integer
                    x-dice-name: data
                    x-dice-required: true
                  success:
                    default: true
                    example: true
                    type: boolean
                    x-dice-name: success
                    x-dice-required: true
                required:
                  - success
                  - data
                type: object
                x-dice-media: application/json
          description: ""
      summary: 项目新建
      tags:
        - 项目管理
    put:
      operationId: 更新项目 /api/projects/{id}
      requestBody:
        content:
          application/json:
            schema:
              example:
                clusterConfig:
                  DEV: Example
                  PROD: Example
                  STAGING: Example
                  TEST: Example
                cpuQuota: 1
                ddHook: Example
                desc: Example
                displayName: Example
                isPublic: true
                logo: Example
                memQuota: 1
                name: Example
              properties:
                clusterConfig:
                  description: 项目的集群设置
                  example:
                    DEV: Example
                    PROD: Example
                    STAGING: Example
                    TEST: Example
                  properties:
                    DEV:
                      example: Example
                      type: string
                      x-dice-name: DEV
                      x-dice-required: true
                    PROD:
                      example: Example
                      type: string
                      x-dice-name: PROD
                      x-dice-required: true
                    STAGING:
                      example: Example
                      type: string
                      x-dice-name: STAGING
                      x-dice-required: true
                    TEST:
                      example: Example
                      type: string
                      x-dice-name: TEST
                      x-dice-required: true
                  required:
                    - DEV
                    - PROD
                    - STAGING
                    - TEST
                  type: object
                  x-dice-name: clusterConfig
                  x-dice-required: true
                cpuQuota:
                  description: cpu配额
                  example: 1
                  type: integer
                  x-dice-name: cpuQuota
                  x-dice-required: true
                ddHook:
                  example: Example
                  type: string
                  x-dice-name: ddHook
                  x-dice-required: true
                desc:
                  example: Example
                  type: string
                  x-dice-name: desc
                  x-dice-required: true
                displayName:
                  example: Example
                  type: string
                  x-dice-name: displayName
                  x-dice-required: true
                isPublic:
                  example: true
                  type: boolean
                  x-dice-name: isPublic
                  x-dice-required: true
                logo:
                  example: Example
                  type: string
                  x-dice-name: logo
                  x-dice-required: true
                memQuota:
                  description: 内存配额
                  example: 1
                  type: integer
                  x-dice-name: memQuota
                  x-dice-required: true
                name:
                  example: Example
                  type: string
                  x-dice-name: name
                  x-dice-required: true
              required:
                - clusterConfig
                - cpuQuota
                - ddHook
                - desc
                - displayName
                - isPublic
                - logo
                - memQuota
                - name
              type: object
              x-dice-media: application/json
      responses:
        "200":
          content:
            application/json:
              schema:
                example:
                  data: 1
                  success: true
                properties:
                  data:
                    description: 项目ID
                    example: 1
                    type: integer
                    x-dice-name: data
                    x-dice-required: true
                  success:
                    default: true
                    example: true
                    type: boolean
                    x-dice-name: success
                    x-dice-required: true
                required:
                  - success
                  - data
                type: object
                x-dice-media: application/json
          description: ""
      summary: 更新项目 /api/projects/{id}
      tags:
        - 项目管理
  /api/projects/{id}:
    parameters:
      - in: path
        name: id
        required: true
        schema:
          example: Example
          type: string
    put:
      operationId: 更新项目
      requestBody:
        content:
          application/json:
            schema:
              example:
                clusterConfig:
                  DEV: Example
                  PROD: Example
                  STAGING: Example
                  TEST: Example
                cpuQuota: 1
                ddHook: Example
                desc: Example
                displayName: Example
                isPublic: true
                logo: Example
                memQuota: 1
                name: Example
              properties:
                clusterConfig:
                  description: 项目集群设置
                  example:
                    DEV: Example
                    PROD: Example
                    STAGING: Example
                    TEST: Example
                  properties:
                    DEV:
                      description: 集群名称
                      example: Example
                      type: string
                      x-dice-name: DEV
                      x-dice-required: true
                    PROD:
                      example: Example
                      type: string
                      x-dice-name: PROD
                      x-dice-required: true
                    STAGING:
                      example: Example
                      type: string
                      x-dice-name: STAGING
                      x-dice-required: true
                    TEST:
                      example: Example
                      type: string
                      x-dice-name: TEST
                      x-dice-required: true
                  required:
                    - DEV
                    - PROD
                    - STAGING
                    - TEST
                  type: object
                  x-dice-name: clusterConfig
                  x-dice-required: true
                cpuQuota:
                  description: cpu配额
                  example: 1
                  type: integer
                  x-dice-name: cpuQuota
                  x-dice-required: true
                ddHook:
                  example: Example
                  type: string
                  x-dice-name: ddHook
                  x-dice-required: false
                desc:
                  description: 项目描述
                  example: Example
                  type: string
                  x-dice-name: desc
                  x-dice-required: false
                displayName:
                  description: 项目别名
                  example: Example
                  type: string
                  x-dice-name: displayName
                  x-dice-required: true
                isPublic:
                  example: true
                  type: boolean
                  x-dice-name: isPublic
                  x-dice-required: false
                logo:
                  description: 项目logo链接
                  example: Example
                  type: string
                  x-dice-name: logo
                  x-dice-required: false
                memQuota:
                  description: 内存配额
                  example: 1
                  type: integer
                  x-dice-name: memQuota
                  x-dice-required: true
                name:
                  description: 项目名称
                  example: Example
                  type: string
                  x-dice-name: name
                  x-dice-required: true
              required:
                - clusterConfig
                - cpuQuota
                - displayName
                - memQuota
                - name
              type: object
              x-dice-media: application/json
              x-dice-name: schema
      responses:
        "200":
          content:
            application/json:
              schema:
                example:
                  data: 1
                  success: true
                properties:
                  data:
                    description: 项目ID
                    example: 1
                    type: integer
                    x-dice-name: data
                    x-dice-required: true
                  success:
                    description: 是否成功
                    example: true
                    type: boolean
                    x-dice-name: success
                    x-dice-required: true
                required:
                  - data
                  - success
                type: object
                x-dice-media: application/json
                x-dice-name: schema
          description: ""
      summary: 更新项目
      tags:
        - 项目管理

components:
  schemas:
    ConfigItem:
      description: 配置项
      example:
        encrypt: true
        key: Example
        type: kv
        value: Example
      properties:
        encrypt:
          description: 是否需要加密，一般填 false
          example: false
          type: boolean
          x-dice-name: encrypt
          x-dice-required: true
        key:
          description: 配置项 Key
          example: Example
          type: string
          x-dice-name: key
          x-dice-required: true
        type:
          description: 配置类型
          enum:
            - kv
          example: kv
          type: string
          x-dice-name: type
          x-dice-required: true
        value:
          description: 配置项 Value
          example: Example
          type: string
          x-dice-name: value
          x-dice-required: true
      required:
        - key
        - value
        - type
        - encrypt
      type: object
      x-dice-forbidden-types:
        - ConfigItem
      x-dice-name: ConfigItem
    GatewayEndpoint:
      example:
        bindDomain:
          - test-gateway.hkci.terminus.io
        id: Example
        scene: unity
      properties:
        bindDomain:
          description: 流量入口绑定的域名
          example:
            - test-gateway.hkci.terminus.io
          items:
            example: test-gateway.hkci.terminus.io
            type: string
            x-dice-name: items
          type: array
          x-dice-name: bindDomain
          x-dice-required: true
        id:
          description: 流量入口 id
          example: Example
          type: string
          x-dice-name: id
          x-dice-required: true
        scene:
          description: 流量入口场景，unity 代表统一域名入口，即 trantor 使用的流量入口
          enum:
            - webapi
            - openapi
            - unity
          example: unity
          type: string
          x-dice-name: scene
          x-dice-required: true
      required:
        - bindDomain
        - scene
        - id
      type: object
      x-dice-forbidden-types:
        - GatewayEndpoint
      x-dice-name: GatewayEndpoint
    StandardResult:
      example:
        err:
          msg: failed
        success: true
      properties:
        err:
          example:
            msg: failed
          properties:
            msg:
              description: 错误具体原因
              example: failed
              type: string
              x-dice-name: msg
              x-dice-required: true
          required:
            - msg
          type: object
          x-dice-name: err
          x-dice-required: true
        success:
          description: 接口是否成功
          example: true
          type: boolean
          x-dice-name: success
          x-dice-required: true
      required:
        - success
        - err
      type: object
      x-dice-forbidden-types:
        - StandardResult
      x-dice-name: StandardResult

tags:
  - name: other
  - name: iterations
  - name: issues
  - name: 应用管理
  - name: 项目管理
  - name: 流水线管理
  - name: API网关